name: NestJS-Backend:CI

on:
  push:
    branches: ['master']
  # Setting an environment variable with the value of a configuration variable


jobs:
  build:
    environment: env
    name: 'Build Image'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env: 
          OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
          DATABASE_URL: ${{ env.DATABASE_URL }}
          NEXT_PUBLIC_API_URL: ${{ env.MY_ENV_VAR }}
          IMAGE_TAG: demo
        run: 
          
          docker build -t ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG . ;
          docker tag ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG;
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG;
          echo "::set-output name=image::${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG";

      - name: Deploy to App Runner
        id: deploy-apprunner
        uses: awslabs/amazon-app-runner-deploy@main        
        with:
          service: ${{ secrets.ECR_REPOSITORY }}
          image: ${{ steps.build-image.outputs.image }}  
          region: ap-southeast-1
          access-role-arn: ${{ secrets.ROLE_ARN }}
          port: 8080
          cpu : 1
          memory : 2  
          wait-for-service-stability-seconds: 600
      
      - name: App Runner output
        run: echo "App runner output ${{ steps.deploy-apprunner.outputs.service-id }}" 

      - name: Logout to Amazon ECR
        if: always()
        run: docker logout ${{steps.login-ecr.outputs.registry}}